### ISSUE TITLE
Running on WSL1 or WSL2?

### ISSUE THREAD

**Issue by ansue1234** [StructuresComp/dismech-rods#9]
It seems like from the documentation that the simulator runs only on linux? Is it possible to run it on Windows through WSL1 or 2? If so, what changes to the installation steps needs to be done?

**Comment by QuantuMope** [comment]
Technically, the simulator should be able to run on windows, but no one has tried it yet. You'd have to install all the software dependencies through the "windows" way of doing it instead of the linux way... up to you whether you want to give it a try, but I would expect it to be a bumpy road.

**Comment by QuantuMope** [comment]
Closing as support for windows is not a priority.
